
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    command: gunicorn raw_code.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: rawcodedb
      POSTGRES_USER: rawuser
      POSTGRES_PASSWORD: rawpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
